### PR TITLE
Merge 'regional_boundary_update' from upstream

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**

### CODE REVIEW

**Comment by climbfuji** [comment]
Someone will need to pull this into an upcoming PR. I suspect it will change the results of all regional tests.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA can we just pull the entire noaa-gfdl dev/emc down to noaa-emc? In addition to the one commit shown here, there are documentation updates in `fv_control.F90` and in the `docs` subdirectory. Then both repositories are fully synced.

**Comment by DusanJovic-NOAA** [comment]
I see only differences in model/fv_regional_bc.F90 when I try to open PR.

**Comment by climbfuji** [comment]
This is weird.

I just changed the submodule pointer from NOAA-EMC dev/emc to NOAA-GFDL dev/emc and I am seeing the changes here:

https://github.com/NOAA-EMC/fv3atm/pull/178 <https://github.com/NOAA-EMC/fv3atm/pull/178>

**Comment by DusanJovic-NOAA** [comment]
In the future all changes should be made to NOAA_EMC repo first. If they go directly to NOAA_GFDL (like documentation and this bug fix in fv_regional_bc.F90) then there's no need for us to maintain this fork, we can just point to GFDL's repo directly from UFS, like we do with ccpp, for example.

**Comment by DusanJovic-NOAA** [comment]
Can we merge this PR?

**Comment by climbfuji** [comment]
> Can we merge this PR?

This should be part of the regression testing conducted in my upcoming ufs-weather-model PR. The fv3atm PR handles the submodule pointer update for GFDL_atmos_cubed_sphere. If you can find a way to update this PR so that it shows the documentation updates, too, then the code I am testing in https://github.com/NOAA-EMC/fv3atm/pull/178 will be identical to your PR.

**Comment by climbfuji** [comment]
Associated PRs:

https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/40
https://github.com/NCAR/ccpp-physics/pull/489
https://github.com/NOAA-EMC/fv3atm/pull/178
https://github.com/ufs-community/ufs-weather-model/pull/208

For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/208.

**Comment by climbfuji** [comment]
Update: after some back and forth, we know that this PR is correct and sufficient. The "missing" documentation changes were merged into NOAA-EMC dev/emc previously without updating the submodule pointer in fv3atm or running the regression tests. This PR #40 will make NOAA-GFDL dev/emc and NOAA-EMC dev/emc identical and should be merged after the testing as outlined in https://github.com/ufs-community/ufs-weather-model/pull/208 is complete.

**Comment by junwang-noaa** [comment]
@climbfuji That is what I think.

**Review by junwang-noaa — APPROVED** [review]
This PR will be committed along with ufs-weather-model PR #208

**Pull request merged**
