### PR TITLE
Update fms_mixedmode to gfdl_atmos_cubed_sphere/dev/emc

### PR DESCRIPTION
**Pull request by MinsukJi-NOAA**

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
I am not sure why all these very old commits (code changes) show up. I checked noaa-gfdl/gfdl_atmos_cubed_sphere/tree/dev/emc, and these commits are indeed there (see, for example, https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/commit/571bff1eb3bce5d58a064998e8f4d8338931c61f), but are not there in noaa-emc/gfdl_atmos_cubed_sphere/tree/fms_mixedmode.

**Review by junwang-noaa — APPROVED** [review]
The code updates look good to me. Have you tested the mixed mode coupled run with your branch?

**Comment by MinsukJi-NOAA** [comment]
> The code updates look good to me. Have you tested the mixed mode coupled run with your branch?

I plan to test the latest ufs-weather-model with mixed mode FMS.

Is there a reason for [NOAA-EMC/fv3atm develop](https://github.com/NOAA-EMC/fv3atm/tree/develop) not pointing to the top of https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/tree/dev/emc?

**Comment by junwang-noaa** [comment]
We were supposed to. The commit in the latest dev/emc has no impact on the
results.

**Review by binli2337 — APPROVED** [review]

**Pull request merged**
