### PR TITLE
Update EMC dev/emc from NCAR dtc/develop 2019/12/17

### PR DESCRIPTION
**Pull request by climbfuji**
This PR:
- adds logic required for the Ferrier-Aligo microphysics (nwat=4) to the FV3 dynamics; this change was made in consultation with Lucas Harris

Associated PRs:
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/11
https://github.com/NCAR/ccpp-framework/pull/246
https://github.com/NCAR/ccpp-physics/pull/372
https://github.com/NOAA-EMC/fv3atm/pull/30
https://github.com/ufs-community/ufs-weather-model/pull/18

For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/18.

### CODE REVIEW

**Review by junwang-noaa — COMMENTED** [review]
Dom,

Do you have an issue associated with the code changes? It looks to me the changes have no impact on non-ccpp code, for CCPP the changes add ql and qs when computing moist heat capacity , it seems this will apply to  the microphysics schemes with nwat=4 for the Ferrier-Aligo microphysics? Do you want to add some physics people to review the code?

**Comment by climbfuji** [comment]
The issue should be the addition of the Ferrier-Aligo microphysics (or the HWRF physics in general, even though this is only the first step). The code changes were made by @ChunxiZhang-NOAA @ericaligo-NOAA and @mzhangw following guidance from Lucas Harris. You can add either or all of them as reviewers. Note that nwat=4 in the "CCPP world" corresponds to Ferrier-Aligo MP, and in the "GFDL world" to Kessler MP at this time.

**Comment by junwang-noaa** [comment]
Added Chunxi and Eric to review the code. I can't add  @mzhangw
<https://github.com/mzhangw> .as reviewer.

**Comment by climbfuji** [comment]
> Added Chunxi and Eric to review the code. I can't add @mzhangw <https://github.com/mzhangw> .as reviewer.
> […](#)

That's correct, not a member of the organization NOAA-EMC. But being tagged means Man was notified. Thanks!

**Review by ericaligo-NOAA — APPROVED** [review]
I've been making tests with these changes and the results look good.

**Review by ericaligo-NOAA — APPROVED** [review]
Changes look okay.  I've been making experiments with these changes and results look good.

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

**Pull request merged**
