### PR TITLE
Skeb sar

### PR DESCRIPTION
**Pull request by pjpegion**
This pull request is to address an issue with NaN values in the halo region of the dissipation estimate (used for SKEB) in the FV3-SAR application.  The does not affect the global model since the halo is filled with values from the other cube faces.

### CODE REVIEW

**Comment by junwang-noaa** [comment]
Phil,

Would you please suggest 2 code reviewers for this pull request? Please let me know if you can't add them to the pull request. Thanks.

**Comment by pjpegion** [comment]
Hi Jun,
 I will suggest Jeff Beck, Rusty benson, and  Dom.  And I don't see how I can add them as reviers.
-Phil

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by pjpegion** [comment]
@junwang-noaa @climbfuji I just updated by skeb_sar branch with dev/emc.  This addition only changes the results for the FV3-SAR, global model is not affected.

**Comment by bensonr** [comment]
@pjpegion just to be clear, the desired behavior for SAR is to smooth the diss_est variable with the values of zero in the halo region?  Other choices are to a) set the halo region to the value of the edge cells or b) mirror interior points into the halo region.

**Comment by pjpegion** [comment]
@bensonr Yes this is the intention.  There is an open science question about which was is the best, but I feel that starting with zero's in the halo region is a good starting point.  I rather have SKEB to too little than too much.

**Review by bensonr — APPROVED** [review]
approved

**Review by climbfuji — APPROVED** [review]
Looks good to me.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
