### PR TITLE
Add an option to use zero-gradient BC to reconstruct interface u/v for height advection; change dz_min as a input

### PR DESCRIPTION
**Pull request by XiaqiongZhou-NOAA**
1)Add an option to use original BC or zero-gradient BC to reconstruct interface u/v with PSM for height advection

2)Change dz_min as a namelist input

##Issue(s) addressed

This is used to solve some model crashes in GFSv16 and regional forecasts.

##Testing

This is tested for GFSv16, regional forecast and idealized mountain wave tests.
This new BC option is not changing forecast performance and results significantly.
It is not change regression test baseline since the default setting remains the same as the original

##Dependencies
https://github.com/ufs-community/ufs-weather-model/pull/369
https://github.com/NOAA-EMC/fv3atm/pull/232

### CODE REVIEW

**Comment by climbfuji** [comment]
# New dependencies 01/20/2021

https://github.com/noaa-psd/stochastic_physics/pull/36
https://github.com/NCAR/ccpp-physics/pull/558
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/53
https://github.com/NOAA-EMC/fv3atm/pull/239
https://github.com/ufs-community/ufs-weather-model/pull/386

**Comment by climbfuji** [comment]
@junwang-noaa @DusanJovic-NOAA Please assign reviewers when you get the chance. Thanks!

**Comment by lharris4** [comment]
The diff makes it look like all of nh_utils.F90 has been re-written. What precisely are the differences in these two versions?

**Comment by XiaqiongZhou-NOAA** [comment]
> The diff makes it look like all of nh_utils.F90 has been re-written. What precisely are the differences in these two versions?
Lucas:
You can change the setting when reviewing the file "Hide whitespace changes" to see the differences. It seems there are some format changes

**Review by yangfanglin — APPROVED** [review]
The updates look fine for me.  The dz_min adjustment now starts from the surface as SJ Lin coded .   An option is added to apply  non-slippery wind profile reconstruction.

**Review by bensonr — APPROVED** [review]
These look good to me.

**Review by lharris4 — APPROVED** [review]
Looks fine to me, as the original behavior can be recovered by namelist options at runtime. Every FV3 user needs to tailor the dynamics to their own needs. The reduction in order at the lower boundary may change the behavior of orographic flows and needs to be closely monitored. Problems arising from the physics need to be fixed rather than relying on the dynamics to cover them up. But otherwise the change is OK.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
