### PR TITLE
Bugfix for regional runs when dycore is compiled in double precision

### PR DESCRIPTION
**Pull request by climbfuji**
This PR fixes issue https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/issues/24.

It also adds one additional line to the initial printout, which we found useful to make sure that all constants and tracers are set up correctly.

### CODE REVIEW

**Comment by climbfuji** [comment]
@DusanJovic-NOAA @junwang-noaa @ligiabernardet @bensonr @ChunxiZhang-NOAA @BinLiu-NOAA @JeffBeck-NOAA @binli2337

**Review by bensonr — APPROVED** [review]

**Comment by climbfuji** [comment]
@mzhangw

**Review by bensonr — COMMENTED** [review]
buf1-4 are now allocatable variables, but the count argument for irecv is still using the ibufexch parameter.  I recommend changing the count in the irecv be the size of buf1 and buf2 respectively.

**Comment by climbfuji** [comment]
> buf1-4 are now allocatable variables, but the count argument for irecv is still using the ibufexch parameter. I recommend changing the count in the irecv be the size of buf1 and buf2 respectively.

Good catch. Thanks very much. Will cleanup!

**Comment by climbfuji** [comment]
> > buf1-4 are now allocatable variables, but the count argument for irecv is still using the ibufexch parameter. I recommend changing the count in the irecv be the size of buf1 and buf2 respectively.
> 
> Good catch. Thanks very much. Will cleanup!

I fixed this - removed ibufexch entirely and used size(bufX) in the messages (since the count isn't known at the time the first MPI commands occur). I reran the tests on Cheyenne, it compiles and runs in DEBUG mode for both 32bit and 64bit without crashing, and the PROD runs in 64-bit give b4b identical results from run to run (which was the issue that triggered this PR in the first place).

**Review by bensonr — COMMENTED** [review]
Changes look consistent.

I would recommend some inline comments or even protection logic to ensure buffering/unbuffering goes as planned.  Any future modification to the logic needs to understand index changes must be thoroughly tested - especially when packing multiple variables into the same buffer.

**Comment by climbfuji** [comment]
> Changes look consistent.
> 
> I would recommend some inline comments or even protection logic to ensure buffering/unbuffering goes as planned. Any future modification to the logic needs to understand index changes must be thoroughly tested - especially when packing multiple variables into the same buffer.

@bensonr does this look better? It still works on Cheyenne as expected.

**Review by bensonr — APPROVED** [review]
Looks good

**Comment by climbfuji** [comment]
Associated PRs:
https://github.com/NOAA-EMC/GFDL_atmos_cubed_sphere/pull/25
https://github.com/NOAA-EMC/fv3atm/pull/133
https://github.com/ufs-community/ufs-weather-model/pull/155

For regression testing, see https://github.com/ufs-community/ufs-weather-model/pull/155.

**Review by junwang-noaa — APPROVED** [review]

**Pull request merged**
